import { activeOrderPhoto, dishPhoto, promotionPhoto, restaurantPhoto } from './assets';
import type { HomeCategory, MenuItem, Offer, Promotion, Restaurant } from './types';

/**
 * The catalogue, written to the Home board's content (frame 48:19762).
 *
 * The ids are unchanged so the menus below still attach to the right
 * restaurant; only the presentation the board specifies — name, locality,
 * rating, delivery and photograph — was brought over, and each cuisine still
 * matches the menu it carries.
 */
export const mockRestaurants: Restaurant[] = [
  {
    id: 'r4',
    name: 'Burger House',
    imageUrl: restaurantPhoto.burgerHouse,
    rating: 4.8,
    cuisine: 'Hambúrgueres',
    deliveryTimeMinutes: 25,
    deliveryFee: 1000,
    description: 'Hambúrgueres suculentos e batatas crocantes em Talatona.',
    distanceKm: 1.2,
    reviewCount: 1248,
    minOrderValue: 4500,
    reviews: [
      {
        id: 'r4-rev1',
        author: 'Mário',
        rating: 5,
        comment: 'Chegou quente e o molho é mesmo especial. Vou pedir outra vez.',
      },
      {
        id: 'r4-rev2',
        author: 'Tânia',
        rating: 4,
        comment: 'Hambúrguer no ponto. A batata podia vir mais crocante.',
      },
    ],
    neighbourhood: 'Talatona',
    hasPromotion: true,
    promotionLabel: '-20%',
  },
  {
    id: 'r1',
    name: 'Sabores da Banda',
    imageUrl: restaurantPhoto.saboresDaBanda,
    rating: 4.8,
    cuisine: 'Angolana',
    deliveryTimeMinutes: 25,
    deliveryFee: 1000,
    description: 'Sabores autênticos da Banda, direto para a sua mesa.',
    distanceKm: 2.4,
    reviewCount: 864,
    minOrderValue: 5000,
    reviews: [
      {
        id: 'r1-rev1',
        author: 'Eunice',
        rating: 5,
        comment: 'O calulu sabe mesmo a casa da avó. Porções generosas.',
      },
      {
        id: 'r1-rev2',
        author: 'Paulo',
        rating: 4,
        comment: 'Entrega dentro do tempo e comida bem embalada.',
      },
    ],
    neighbourhood: 'Maianga',
  },
  {
    id: 'r3',
    name: 'Forno 27',
    imageUrl: restaurantPhoto.forno27,
    rating: 4.8,
    cuisine: 'Pizza',
    deliveryTimeMinutes: 25,
    deliveryFee: 1000,
    description: 'Pizzas artesanais assadas em forno a lenha no Morro Bento.',
    distanceKm: 1.5,
    reviewCount: 1032,
    minOrderValue: 4000,
    reviews: [
      {
        id: 'r3-rev1',
        author: 'Hélder',
        rating: 5,
        comment: 'Massa fina e bem assada, dá para sentir o forno a lenha.',
      },
      {
        id: 'r3-rev2',
        author: 'Marta',
        rating: 4,
        comment: 'Boa pizza, só achei o queijo um pouco escasso.',
      },
    ],
    neighbourhood: 'Morro Bento',
  },
  {
    id: 'r5',
    name: 'Brasa do Sul',
    imageUrl: restaurantPhoto.saboresDaBanda,
    rating: 4.8,
    cuisine: 'Grelhados',
    deliveryTimeMinutes: 25,
    deliveryFee: 1000,
    description: 'Grelhados na brasa com o sabor tradicional angolano.',
    distanceKm: 3.4,
    reviewCount: 517,
    minOrderValue: 6000,
    reviews: [
      {
        id: 'r5-rev1',
        author: 'Nelson',
        rating: 5,
        comment: 'A picanha vem no ponto que pedi. Recomendo o combo.',
      },
      {
        id: 'r5-rev2',
        author: 'Isabel',
        rating: 4,
        comment: 'Grelhados muito bons, mas demorou um pouco mais do que o previsto.',
      },
    ],
    neighbourhood: 'Benfica',
    hasPromotion: true,
    promotionLabel: 'Entrega grátis',
  },
  {
    id: 'r2',
    name: 'Cantinho da Kianda',
    imageUrl: restaurantPhoto.cantinhoDaKianda,
    rating: 4.8,
    cuisine: 'Peixe',
    deliveryTimeMinutes: 20,
    deliveryFee: 1500,
    description: 'Peixe fresco do dia, preparado à moda da casa.',
    distanceKm: 0.9,
    reviewCount: 743,
    minOrderValue: 5500,
    reviews: [
      {
        id: 'r2-rev1',
        author: 'Domingos',
        rating: 5,
        comment: 'Peixe fresco mesmo, dá para notar logo na primeira garfada.',
      },
      {
        id: 'r2-rev2',
        author: 'Luísa',
        rating: 5,
        comment: 'Já é a terceira vez que peço. Nunca desilude.',
      },
    ],
    neighbourhood: 'Ingombota',
  },
  {
    id: 'r7',
    name: 'Frango & Companhia',
    imageUrl: restaurantPhoto.frangoECompanhia,
    rating: 4.8,
    cuisine: 'Frango',
    deliveryTimeMinutes: 25,
    deliveryFee: 1000,
    description: 'Frango grelhado e acompanhamentos no Kilamba.',
    distanceKm: 2.9,
    reviewCount: 926,
    minOrderValue: 3500,
    reviews: [
      {
        id: 'r7-rev1',
        author: 'Kiesse',
        rating: 5,
        comment: 'Frango bem temperado e o molho pirí-pirí é na medida certa.',
      },
      {
        id: 'r7-rev2',
        author: 'Rita',
        rating: 4,
        comment: 'Boa relação qualidade-preço para a família toda.',
      },
    ],
    neighbourhood: 'Kilamba',
  },
  {
    id: 'r6',
    name: 'Sushi Luanda',
    imageUrl: restaurantPhoto.cantinhoDaKianda,
    rating: 4.6,
    cuisine: 'Japonesa',
    deliveryTimeMinutes: 45,
    deliveryFee: 900,
    description: 'Sushi fresco e combinados japoneses no coração de Luanda.',
    distanceKm: 6.2,
    reviewCount: 388,
    minOrderValue: 8000,
    reviews: [
      {
        id: 'r6-rev1',
        author: 'André',
        rating: 5,
        comment: 'Peixe cortado na hora e arroz bem temperado. Surpreendeu.',
      },
      {
        id: 'r6-rev2',
        author: 'Sofia',
        rating: 4,
        comment: 'Combinado bonito e fresco, só a entrega é que tarda.',
      },
    ],
    neighbourhood: 'Talatona',
  },
];

export const mockMenuItems: MenuItem[] = [
  {
    id: 'r1-1',
    restaurantId: 'r1',
    name: 'Calulu de Peixe',
    description: 'Peixe seco cozinhado com quiabo, jinguba e óleo de palma.',
    price: 4500,
    imageUrl: restaurantPhoto.saboresDaBanda,
    category: 'Pratos Principais',
  },
  {
    id: 'r1-2',
    restaurantId: 'r1',
    name: 'Funge com Feijão',
    description: 'Funge de bombó acompanhado de feijão de óleo de palma.',
    price: 3200,
    imageUrl: restaurantPhoto.saboresDaBanda,
    category: 'Pratos Principais',
  },
  {
    id: 'r1-3',
    restaurantId: 'r1',
    name: 'Gindungo Frito',
    description: 'Entrada picante de pimenta gindungo frita.',
    price: 1500,
    imageUrl: restaurantPhoto.saboresDaBanda,
    category: 'Entradas',
  },
  {
    id: 'r1-4',
    restaurantId: 'r1',
    name: 'Kissangua',
    description: 'Bebida tradicional fermentada de milho.',
    price: 1000,
    imageUrl: restaurantPhoto.saboresDaBanda,
    category: 'Bebidas',
  },
  {
    id: 'r2-1',
    restaurantId: 'r2',
    name: 'Camarão Grelhado',
    description: 'Camarão fresco grelhado com alho e limão.',
    price: 6500,
    imageUrl: restaurantPhoto.cantinhoDaKianda,
    category: 'Pratos Principais',
  },
  {
    id: 'r2-2',
    restaurantId: 'r2',
    name: 'Caranguejo à Moda da Casa',
    description: 'Caranguejo cozido no molho da casa.',
    price: 7200,
    imageUrl: restaurantPhoto.cantinhoDaKianda,
    category: 'Pratos Principais',
  },
  {
    id: 'r2-3',
    restaurantId: 'r2',
    name: 'Salada de Polvo',
    description: 'Polvo cozido com cebola, azeite e coentros.',
    price: 3800,
    imageUrl: restaurantPhoto.cantinhoDaKianda,
    category: 'Entradas',
  },
  {
    id: 'r2-4',
    restaurantId: 'r2',
    name: 'Sumo de Maboque',
    description: 'Sumo natural de fruta maboque.',
    price: 1200,
    imageUrl: restaurantPhoto.cantinhoDaKianda,
    category: 'Bebidas',
  },
  {
    id: 'r3-1',
    restaurantId: 'r3',
    name: 'Pizza Margherita',
    description: 'Molho de tomate, mozzarella e manjericão fresco.',
    price: 4000,
    imageUrl: restaurantPhoto.forno27,
    category: 'Pratos Principais',
  },
  {
    id: 'r3-2',
    restaurantId: 'r3',
    name: 'Pizza Pepperoni',
    description: 'Molho de tomate, mozzarella e pepperoni.',
    price: 4800,
    imageUrl: restaurantPhoto.forno27,
    category: 'Pratos Principais',
  },
  {
    id: 'r3-3',
    restaurantId: 'r3',
    name: 'Bruschetta',
    description: 'Pão tostado com tomate, alho e azeite.',
    price: 2000,
    imageUrl: restaurantPhoto.forno27,
    category: 'Entradas',
  },
  {
    id: 'r3-4',
    restaurantId: 'r3',
    name: 'Tiramisu',
    description: 'Sobremesa italiana com café e mascarpone.',
    price: 2500,
    imageUrl: restaurantPhoto.forno27,
    category: 'Sobremesas',
  },
  {
    id: 'r4-1',
    restaurantId: 'r4',
    name: 'Cheeseburger Clássico',
    description: 'Hambúrguer de carne, queijo cheddar, alface e tomate.',
    price: 3000,
    imageUrl: dishPhoto.classicBurger,
    category: 'Pratos Principais',
  },
  {
    id: 'r4-2',
    restaurantId: 'r4',
    name: 'Burger Duplo Bacon',
    description: 'Duas carnes, bacon crocante e molho especial.',
    price: 3800,
    previousPrice: 4600,
    imageUrl: dishPhoto.doubleBurger,
    category: 'Pratos Principais',
  },
  {
    id: 'r4-3',
    restaurantId: 'r4',
    name: 'Batata Frita',
    description: 'Porção de batata frita crocante.',
    price: 1200,
    imageUrl: dishPhoto.fries,
    category: 'Entradas',
  },
  {
    id: 'r4-4',
    restaurantId: 'r4',
    name: 'Milkshake de Chocolate',
    description: 'Milkshake cremoso de chocolate.',
    price: 1800,
    imageUrl: dishPhoto.combo,
    category: 'Bebidas',
  },
  {
    id: 'r5-1',
    restaurantId: 'r5',
    name: 'Espetada de Frango',
    description: 'Espetada de frango grelhado com pimentos.',
    price: 4200,
    imageUrl: restaurantPhoto.saboresDaBanda,
    category: 'Pratos Principais',
  },
  {
    id: 'r5-2',
    restaurantId: 'r5',
    name: 'Costela de Porco Grelhada',
    description: 'Costela suína grelhada com molho barbecue.',
    price: 5200,
    imageUrl: restaurantPhoto.saboresDaBanda,
    category: 'Pratos Principais',
  },
  {
    id: 'r5-3',
    restaurantId: 'r5',
    name: 'Salada Mista',
    description: 'Alface, tomate, cebola e pepino.',
    price: 1500,
    imageUrl: restaurantPhoto.saboresDaBanda,
    category: 'Entradas',
  },
  {
    id: 'r5-4',
    restaurantId: 'r5',
    name: 'Cerveja Cuca',
    description: 'Cerveja angolana gelada.',
    price: 1000,
    imageUrl: restaurantPhoto.saboresDaBanda,
    category: 'Bebidas',
  },
  {
    id: 'r6-1',
    restaurantId: 'r6',
    name: 'Combo Sashimi',
    description: '12 peças variadas de sashimi fresco.',
    price: 7500,
    imageUrl: restaurantPhoto.cantinhoDaKianda,
    category: 'Pratos Principais',
  },
  {
    id: 'r6-2',
    restaurantId: 'r6',
    name: 'Uramaki Philadelphia',
    description: 'Salmão, queijo creme e pepino.',
    price: 5500,
    imageUrl: restaurantPhoto.cantinhoDaKianda,
    category: 'Pratos Principais',
  },
  {
    id: 'r6-3',
    restaurantId: 'r6',
    name: 'Edamame',
    description: 'Vagens de soja cozidas com sal marinho.',
    price: 1800,
    imageUrl: restaurantPhoto.cantinhoDaKianda,
    category: 'Entradas',
  },
  {
    id: 'r6-4',
    restaurantId: 'r6',
    name: 'Chá Verde Gelado',
    description: 'Chá verde japonês servido gelado.',
    price: 1100,
    imageUrl: restaurantPhoto.cantinhoDaKianda,
    category: 'Bebidas',
  },
  {
    id: 'r7-1',
    restaurantId: 'r7',
    name: 'Moamba de Galinha',
    description: 'Galinha cozida em molho de ginguba com quiabo.',
    price: 3800,
    imageUrl: restaurantPhoto.frangoECompanhia,
    category: 'Pratos Principais',
  },
  {
    id: 'r7-2',
    restaurantId: 'r7',
    name: 'Cacimba de Peixe',
    description: 'Caldo tradicional de peixe com gengibre e alho.',
    price: 4200,
    imageUrl: restaurantPhoto.frangoECompanhia,
    category: 'Pratos Principais',
  },
];

export const mockOffers: Offer[] = [
  {
    id: 'o1',
    imageUrl: 'https://loremflickr.com/400/300/food,pizza?lock=201',
    badgeLabel: 'PROMOÇÃO',
    title: '50% Off em Pizzas',
    subtitle: 'Válido até hoje às 22h',
  },
  {
    id: 'o2',
    imageUrl: 'https://loremflickr.com/400/300/food,burger?lock=202',
    badgeLabel: 'COMBO',
    title: 'Burger + Batata + Bebida',
    subtitle: 'Peça já em Ingombota',
  },
  {
    id: 'o3',
    imageUrl: 'https://loremflickr.com/400/300/food,bbq?lock=203',
    badgeLabel: 'NOVO',
    title: 'Grelhados Muxima',
    subtitle: 'Experimente o novo menu de brasa',
  },
  {
    id: 'o4',
    imageUrl: 'https://loremflickr.com/400/300/food,seafood?lock=204',
    badgeLabel: 'FRETE GRÁTIS',
    title: 'Marisco sem taxa de entrega',
    subtitle: 'Só esta semana no Kinaxixe',
  },
];

/** The two merchandised banners (nodes 48:19819 and 48:19885). */
export const mockPromotions: Promotion[] = [
  {
    id: 'p1',
    title: '20% no almoço',
    subtitle: 'Sabores de Talatona até às 14h',
    ctaLabel: 'Ver opções',
    imageUrl: promotionPhoto,
    tone: 'featured',
  },
  {
    id: 'p2',
    title: 'Combos desde 7.500 Kz',
    subtitle: 'Partilha mais, paga menos',
    ctaLabel: 'Ver combos',
    imageUrl: promotionPhoto,
    tone: 'limited',
  },
];

/**
 * The craving tiles (node 48:19801).
 *
 * Deliberately not derived from `cuisine`: the board curates four appetites
 * ("Hambúrguer", "Pizza", "Frango", "Sushi"), which is a shorter and more
 * concrete list than the cuisines the catalogue happens to contain.
 */
export const mockHomeCategories: HomeCategory[] = [
  { id: 'hamburguer', label: 'Hambúrguer', keywords: ['burger', 'fast food', 'hambúrguer'] },
  { id: 'pizza', label: 'Pizza', keywords: ['pizza', 'italiana'] },
  { id: 'frango', label: 'Frango', keywords: ['frango', 'galinha', 'grelhado'] },
  { id: 'sushi', label: 'Sushi', keywords: ['sushi', 'japonesa', 'marisco'] },
];

/**
 * The last order, for "Pedir novamente" (node 48:19910).
 *
 * Stored as a restaurant reference plus a total rather than as a second copy
 * of the restaurant, so the card renders the same catalogue entry every other
 * section does.
 */
export const mockLastOrder = {
  restaurantId: 'r7',
  total: 12000,
} as const;
